version: '3.1'
services:
  db:
    image: library/postgres:12-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345678
        POSTGRES_DB: postgres